services:
  postgres:
    image: postgres:15
    container_name: postgres_monit
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monit
  monitoramento-reservatorio:
    container_name: monitoramento-reservatorio
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - monit
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  monit:
    driver: bridge
